import 'package:flutter/material.dart';

import 'permission_definition.dart';

class PermissionCatalog {
  static const String categoryVisibility = 'VISIBILIDADE';
  static const String categoryStudents = 'ALUNOS';
  static const String categoryAttendance = 'CHAMADA E AVALIAÃÃES';
  static const String categoryEventsGeneral = 'EVENTOS â GERAL';
  static const String categoryEventsParticipants = 'EVENTOS â PARTICIPANTES';
  static const String categoryEventsPayments = 'EVENTOS â PAGAMENTOS';
  static const String categoryEventsFinancial = 'EVENTOS â FINANCEIRO';
  static const String categoryUsers = 'USUÃRIOS';
  static const String categoryUniforms = 'UNIFORMES';
  static const String categorySystemAdmin = 'SISTEMA / ADMIN';
  static const String categorySystemConfig = 'SISTEMA / CONFIGURAÃÃES';

  static const List<String> categoriesForUserDetails = [
    categoryVisibility,
    categoryStudents,
    categoryAttendance,
    categoryEventsGeneral,
    categoryEventsParticipants,
    categoryEventsPayments,
    categoryEventsFinancial,
    categoryUsers,
    categoryUniforms,
    categorySystemAdmin,
    categorySystemConfig,
  ];

  static const List<PermissionDefinition> all = [
    PermissionDefinition(
      title: 'Acessar eventos',
      description: 'Mostra o menu Eventos e permite abrir a tela de eventos.',
      key: 'pode_acessar_eventos',
      aliases: ['podeAcessarEventos', 'pode_ver_eventos'],
      icon: Icons.event_rounded,
      category: categoryVisibility,
    ),
    PermissionDefinition(
      title: 'Acessar inscriÃ§Ãµes',
      description: 'Mostra o menu InscriÃ§Ãµes no app.',
      key: 'pode_acessar_inscricoes',
      aliases: ['podeAcessarInscricoes'],
      icon: Icons.app_registration_rounded,
      category: categoryVisibility,
    ),
    PermissionDefinition(
      title: 'Acessar uniformes',
      description: 'Mostra o menu Uniformes no app.',
      key: 'pode_acessar_uniformes',
      aliases: ['podeAcessarUniformes'],
      icon: Icons.shopping_bag_rounded,
      category: categoryVisibility,
    ),
    PermissionDefinition(
      title: 'Acessar associaÃ§Ã£o',
      description: 'Mostra o menu AssociaÃ§Ã£o no app.',
      key: 'pode_acessar_associacao',
      aliases: ['podeAcessarAssociacao'],
      icon: Icons.people_outline_rounded,
      category: categoryVisibility,
    ),
    PermissionDefinition(
      title: 'Mostrar alunos na barra lateral',
      description:
          'Mostra o menu Alunos na barra lateral do app. NÃ£o substitui a permissÃ£o de ver alunos.',
      key: 'pode_mostrar_alunos_drawer',
      aliases: ['podeMostrarAlunosDrawer'],
      icon: Icons.menu_open_rounded,
      category: categoryVisibility,
    ),
    PermissionDefinition(
      title: 'Acessar rifas',
      description: 'Mostra o menu Rifas no app.',
      key: 'pode_acessar_rifas',
      aliases: ['podeAcessarRifas'],
      icon: Icons.confirmation_number_rounded,
      category: categoryVisibility,
    ),
    PermissionDefinition(
      title: 'Ver eventos',
      description: 'Permite visualizar a lista de eventos.',
      key: 'pode_ver_eventos',
      aliases: ['podeAcessarEventos', 'pode_acessar_eventos'],
      icon: Icons.visibility_rounded,
      category: categoryEventsGeneral,
    ),
    PermissionDefinition(
      title: 'Ver eventos em andamento',
      description: 'Permite abrir eventos em andamento.',
      key: 'pode_ver_eventos_andamento',
      icon: Icons.pending_actions_rounded,
      category: categoryEventsGeneral,
    ),
    PermissionDefinition(
      title: 'Criar evento',
      description: 'Permite criar novos eventos.',
      key: 'pode_criar_evento',
      icon: Icons.add_circle_rounded,
      category: categoryEventsGeneral,
    ),
    PermissionDefinition(
      title: 'Editar evento',
      description: 'Permite editar dados de eventos existentes.',
      key: 'pode_editar_evento',
      icon: Icons.edit_calendar_rounded,
      category: categoryEventsGeneral,
    ),
    PermissionDefinition(
      title: 'Excluir evento',
      description: 'Permite excluir eventos.',
      key: 'pode_excluir_evento',
      icon: Icons.delete_forever_rounded,
      category: categoryEventsGeneral,
    ),
    PermissionDefinition(
      title: 'Finalizar evento',
      description: 'Permite finalizar evento em andamento.',
      key: 'pode_finalizar_evento',
      icon: Icons.check_circle_rounded,
      category: categoryEventsGeneral,
    ),
    PermissionDefinition(
      title: 'Reabrir evento',
      description: 'Permite reabrir ou iniciar evento, quando existir.',
      key: 'pode_reabrir_evento',
      aliases: ['pode_iniciar_evento'],
      icon: Icons.replay_circle_filled_rounded,
      category: categoryEventsGeneral,
    ),
    PermissionDefinition(
      title: 'Gerenciar participantes',
      description: 'Permite abrir o mÃ³dulo de participantes do evento.',
      key: 'pode_gerenciar_participantes_evento',
      aliases: ['pode_gerenciar_participantes'],
      icon: Icons.groups_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Ver participantes',
      description: 'Permite visualizar a lista de participantes do evento.',
      key: 'pode_ver_participantes_evento',
      aliases: ['pode_visualizar_participantes_evento'],
      icon: Icons.visibility_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Ver detalhe da participacao',
      description: 'Permite abrir o detalhe da participacao do aluno.',
      key: 'pode_ver_detalhe_participacao_evento',
      aliases: ['pode_visualizar_detalhe_participacao_evento'],
      icon: Icons.badge_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Adicionar participante',
      description: 'Permite adicionar alunos ao evento.',
      key: 'pode_adicionar_participante_evento',
      aliases: [
        'pode_adcionar_aluno_a_eventos',
        'pode_adicionar_aluno_a_eventos',
      ],
      icon: Icons.person_add_alt_1_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Editar participaÃ§Ã£o',
      description: 'Permite editar dados de participaÃ§Ã£o do aluno no evento.',
      key: 'pode_editar_participacao_evento',
      aliases: ['pode_editar_participante_evento'],
      icon: Icons.manage_accounts_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Editar dados da participacao',
      description: 'Permite editar dados gerais da participacao.',
      key: 'pode_editar_dados_participacao_evento',
      aliases: ['pode_editar_participante_evento'],
      icon: Icons.edit_note_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Editar camisa da participacao',
      description:
          'Permite alterar tamanho, modelagem, tipo e entrega de camisa.',
      key: 'pode_editar_camisa_participacao_evento',
      aliases: ['pode_editar_camisa_evento'],
      icon: Icons.checkroom_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Editar graduacao da participacao',
      description: 'Permite alterar graduacao/corda da participacao.',
      key: 'pode_editar_graduacao_participacao_evento',
      aliases: ['pode_editar_graduacao_evento'],
      icon: Icons.emoji_events_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Editar status de pagamento',
      description: 'Permite alterar status de pagamento da participacao.',
      key: 'pode_editar_status_pagamento_participacao_evento',
      aliases: ['pode_editar_status_pagamento_evento'],
      icon: Icons.price_check_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Editar observacoes da participacao',
      description: 'Permite editar observacoes internas da participacao.',
      key: 'pode_editar_observacoes_participacao_evento',
      aliases: ['pode_editar_observacoes_evento'],
      icon: Icons.notes_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Editar status da participacao',
      description: 'Permite alterar o status geral da participacao.',
      key: 'pode_editar_status_participacao_evento',
      aliases: ['pode_alterar_status_participacao_evento'],
      icon: Icons.published_with_changes_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Remover participante',
      description: 'Permite remover alunos do evento.',
      key: 'pode_remover_participante_evento',
      aliases: ['pode_remover_alunos_de_eventos'],
      icon: Icons.person_remove_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Concluir participaÃ§Ã£o',
      description: 'Permite marcar/concluir participaÃ§Ã£o do aluno no evento.',
      key: 'pode_concluir_participacao_evento',
      icon: Icons.done_all_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Cancelar participacao',
      description: 'Permite cancelar participacao no evento.',
      key: 'pode_cancelar_participacao_evento',
      aliases: ['pode_cancelar_participacao'],
      icon: Icons.cancel_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Desfazer conclusao da participacao',
      description: 'Permite desfazer conclusao/finalizacao individual.',
      key: 'pode_desfazer_conclusao_participacao_evento',
      aliases: ['pode_desfazer_conclusao_participacao'],
      icon: Icons.undo_rounded,
      category: categoryEventsParticipants,
    ),
    PermissionDefinition(
      title: 'Registrar pagamento',
      description: 'Permite lanÃ§ar pagamentos na participaÃ§Ã£o do aluno.',
      key: 'pode_registrar_pagamento_evento',
      aliases: ['pode_registrar_pagamento'],
      icon: Icons.add_card_rounded,
      category: categoryEventsPayments,
    ),
    PermissionDefinition(
      title: 'Editar pagamento',
      description:
          'Permite corrigir valor, forma, status e observaÃ§Ãµes de pagamentos jÃ¡ lanÃ§ados.',
      key: 'pode_editar_pagamento_evento',
      aliases: ['pode_editar_pagamento'],
      icon: Icons.edit_note_rounded,
      category: categoryEventsPayments,
    ),
    PermissionDefinition(
      title: 'Excluir pagamento',
      description:
          'Permite apagar pagamentos e recalcular o saldo da participaÃ§Ã£o.',
      key: 'pode_excluir_pagamento_evento',
      aliases: ['pode_excluir_pagamento'],
      icon: Icons.delete_sweep_rounded,
      category: categoryEventsPayments,
    ),
    PermissionDefinition(
      title: 'Marcar patrocinio',
      description: 'Permite marcar pagamento/participante como patrocinado.',
      key: 'pode_marcar_patrocinio_evento',
      aliases: ['pode_marcar_patrocinio'],
      icon: Icons.volunteer_activism_rounded,
      category: categoryEventsPayments,
    ),
    PermissionDefinition(
      title: 'Ver financeiro do evento',
      description: 'Permite visualizar informacoes financeiras do evento.',
      key: 'pode_ver_financeiro_evento',
      aliases: ['pode_visualizar_financeiro_evento'],
      icon: Icons.account_balance_wallet_rounded,
      category: categoryEventsPayments,
    ),
    PermissionDefinition(
      title: 'Gerenciar gastos',
      description: 'Permite adicionar, editar e excluir gastos do evento.',
      key: 'pode_gerenciar_gastos_evento',
      aliases: ['pode_gerenciar_financeiro', 'pode_gerenciar_taxas'],
      icon: Icons.payments_rounded,
      category: categoryEventsFinancial,
    ),
    PermissionDefinition(
      title: 'Gerenciar patrocinadores',
      description: 'Permite gerenciar patrocinadores e apoios do evento.',
      key: 'pode_gerenciar_patrocinadores_evento',
      aliases: ['pode_gerenciar_patrocinadores'],
      icon: Icons.handshake_rounded,
      category: categoryEventsFinancial,
    ),
    PermissionDefinition(
      title: 'Gerenciar camisas',
      description: 'Permite gerenciar camisas, pagamentos e entregas.',
      key: 'pode_gerenciar_camisas_evento',
      aliases: ['pode_gerenciar_camisas'],
      icon: Icons.checkroom_rounded,
      category: categoryEventsFinancial,
    ),
    PermissionDefinition(
      title: 'Ver relatÃ³rios do evento',
      description: 'Permite abrir relatÃ³rios financeiros e listas do evento.',
      key: 'pode_ver_relatorio_evento',
      aliases: ['pode_ver_relatorios'],
      icon: Icons.assessment_rounded,
      category: categoryEventsFinancial,
    ),
    PermissionDefinition(
      title: 'Gerar certificados',
      description: 'Permite gerar certificados do evento.',
      key: 'pode_gerar_certificados_evento',
      aliases: ['pode_gerar_certificados'],
      icon: Icons.card_membership_rounded,
      category: categoryEventsFinancial,
    ),
    PermissionDefinition(
      title: 'Configurar certificados do evento',
      description: 'Permite configurar certificados especificos do evento.',
      key: 'pode_configurar_certificados_evento',
      aliases: ['pode_configurar_certificado_evento'],
      icon: Icons.tune_rounded,
      category: categoryEventsFinancial,
    ),
    PermissionDefinition(
      title: 'Adicionar aluno',
      description: 'Permite adicionar novos alunos.',
      key: 'pode_adicionar_aluno',
      icon: Icons.person_add_rounded,
      category: categoryStudents,
    ),
    PermissionDefinition(
      title: 'Visualizar alunos',
      description: 'Permite ver lista de alunos.',
      key: 'pode_visualizar_alunos',
      icon: Icons.visibility_rounded,
      category: categoryStudents,
    ),
    PermissionDefinition(
      title: 'Editar aluno',
      description: 'Permite editar informaÃ§Ãµes de alunos.',
      key: 'pode_editar_aluno',
      icon: Icons.edit_rounded,
      category: categoryStudents,
    ),
    PermissionDefinition(
      title: 'Excluir aluno',
      description: 'Permite excluir alunos.',
      key: 'pode_excluir_aluno',
      icon: Icons.delete_rounded,
      category: categoryStudents,
    ),
    PermissionDefinition(
      title: 'Desativar aluno',
      description: 'Permite tornar alunos inativos.',
      key: 'pode_desativar_aluno',
      icon: Icons.person_off_rounded,
      category: categoryStudents,
    ),
    PermissionDefinition(
      title: 'Ativar aluno',
      description: 'Permite reativar alunos inativos.',
      key: 'pode_ativar_alunos',
      icon: Icons.person_add_alt_rounded,
      category: categoryStudents,
    ),
    PermissionDefinition(
      title: 'Mudar turma',
      description: 'Permite transferir alunos entre turmas.',
      key: 'pode_mudar_turma',
      icon: Icons.switch_account_rounded,
      category: categoryStudents,
    ),
    PermissionDefinition(
      title: 'Ver resumo da turma',
      description:
          'Libera o card âResumo da turmaâ com estatÃ­sticas e relatÃ³rios dos alunos da turma.',
      key: 'pode_visualizar_relatorios',
      aliases: ['pode_visualizar_relatorios_turma'],
      icon: Icons.summarize_rounded,
      category: categoryStudents,
    ),
    PermissionDefinition(
      title: 'Fazer chamada',
      description: 'Permite registrar chamada.',
      key: 'pode_fazer_chamada',
      icon: Icons.checklist_rounded,
      category: categoryAttendance,
    ),
    PermissionDefinition(
      title: 'Editar chamada',
      description: 'Permite editar chamadas jÃ¡ salvas.',
      key: 'pode_editar_chamada',
      aliases: ['pode_editar_chamadas', 'podeEditarChamada'],
      icon: Icons.edit_calendar_rounded,
      category: categoryAttendance,
    ),
    PermissionDefinition(
      title: 'Excluir chamada',
      description:
          'Permite excluir/desfazer uma chamada jÃ¡ salva e recalcular os contadores dos alunos.',
      key: 'pode_excluir_chamada',
      aliases: ['pode_excluir_chamadas', 'podeExcluirChamada'],
      icon: Icons.delete_sweep_rounded,
      category: categoryAttendance,
    ),
    PermissionDefinition(
      title: 'Ver lista de chamada',
      description: 'Permite ver histÃ³rico de chamadas.',
      key: 'pode_ver_lista_de_chamada',
      icon: Icons.list_alt_rounded,
      category: categoryAttendance,
    ),
    PermissionDefinition(
      title: 'Avaliar aluno',
      description: 'Permite avaliar comportamento, disciplina e evoluÃ§Ã£o.',
      key: 'pode_avaliar_aluno',
      icon: Icons.star_rate_rounded,
      category: categoryAttendance,
    ),
    PermissionDefinition(
      title: 'Gerenciar usuÃ¡rios',
      description: 'Permite gerenciar usuÃ¡rios e permissÃµes.',
      key: 'pode_gerenciar_usuarios',
      icon: Icons.people_rounded,
      category: categoryUsers,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
    PermissionDefinition(
      title: 'Editar vendas',
      description: 'Permite editar vendas de uniformes.',
      key: 'pode_editar_venda',
      icon: Icons.edit_rounded,
      category: categoryUniforms,
    ),
    PermissionDefinition(
      title: 'Excluir vendas',
      description: 'Permite excluir vendas de uniformes.',
      key: 'pode_excluir_venda',
      icon: Icons.delete_forever_rounded,
      category: categoryUniforms,
    ),
    PermissionDefinition(
      title: 'Editar pedidos',
      description: 'Permite editar pedidos.',
      key: 'pode_editar_pedido',
      icon: Icons.edit_note_rounded,
      category: categoryUniforms,
    ),
    PermissionDefinition(
      title: 'Excluir pedidos',
      description: 'Permite excluir pedidos.',
      key: 'pode_excluir_pedido',
      icon: Icons.delete_sweep_rounded,
      category: categoryUniforms,
    ),
    PermissionDefinition(
      title: 'Gerenciar estoque',
      description: 'Permite gerenciar estoque.',
      key: 'pode_gerenciar_estoque',
      icon: Icons.inventory_rounded,
      category: categoryUniforms,
    ),
    PermissionDefinition(
      title: 'Gerenciar site',
      description: 'Permite gerenciar conteúdo público e páginas do site.',
      key: 'pode_gerenciar_site',
      icon: Icons.public_rounded,
      category: categorySystemAdmin,
    ),
    PermissionDefinition(
      title: 'Gerenciar temas globais',
      description:
          'Permite alterar o tema padrão do app, temas disponíveis para usuários e campanhas visuais.',
      key: 'pode_gerenciar_temas_globais',
      aliases: ['podeGerenciarTemasGlobais'],
      icon: Icons.palette_rounded,
      category: categorySystemConfig,
    ),
    PermissionDefinition(
      title: 'Gerenciar logo do site',
      description: 'Permite alterar a logo exibida no site.',
      key: 'pode_gerenciar_logo_site',
      icon: Icons.image_rounded,
      category: categorySystemAdmin,
    ),
    PermissionDefinition(
      title: 'SaÃºde Firebase',
      description:
          'Permite acessar diagnÃ³stico de banco, storage, functions e uso.',
      key: 'pode_saude_firebase',
      icon: Icons.health_and_safety_rounded,
      category: categorySystemAdmin,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
    PermissionDefinition(
      title: 'Controle de atualizaÃ§Ãµes',
      description:
          'Permite gerenciar versÃµes, APKs e publicaÃ§Ã£o de atualizaÃ§Ãµes.',
      key: 'pode_controle_atualizacoes',
      icon: Icons.system_update_alt_rounded,
      category: categorySystemAdmin,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
    PermissionDefinition(
      title: 'Configurar indicadores de ausÃªncia',
      description: 'Permite configurar alertas de frequÃªncia e ausÃªncia.',
      key: 'pode_configurar_indicadores_ausencia',
      icon: Icons.rule_rounded,
      category: categorySystemAdmin,
    ),
    PermissionDefinition(
      title: 'Configurar chamada',
      description: 'Permite configurar recursos administrativos da chamada.',
      key: 'pode_configurar_chamada',
      icon: Icons.psychology_alt_rounded,
      category: categorySystemAdmin,
    ),
    PermissionDefinition(
      title: 'Gerenciar graduaÃ§Ãµes',
      description: 'Permite criar, editar e organizar graduaÃ§Ãµes do app.',
      key: 'pode_gerenciar_graduacoes',
      icon: Icons.workspace_premium_rounded,
      category: categorySystemAdmin,
    ),
    PermissionDefinition(
      title: 'Gerenciar academias',
      description: 'Permite gerenciar academias, nÃºcleos, turmas e horÃ¡rios.',
      key: 'pode_gerenciar_academias',
      icon: Icons.business_rounded,
      category: categorySystemAdmin,
    ),
    PermissionDefinition(
      title: 'Configurar certificados',
      description: 'Permite configurar modelos e prÃ©vias de certificados.',
      key: 'pode_configurar_certificados',
      icon: Icons.history_edu_rounded,
      category: categorySystemAdmin,
    ),
    PermissionDefinition(
      title: 'Executar migraÃ§Ãµes',
      description: 'Permite acessar ferramentas de migraÃ§Ã£o de dados.',
      key: 'pode_executar_migracoes',
      icon: Icons.sync_alt_rounded,
      category: categorySystemAdmin,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
    PermissionDefinition(
      title: 'Migrar alunos',
      description: 'Permite executar migraÃ§Ã£o de alunos.',
      key: 'pode_migrar_alunos',
      icon: Icons.people_alt_rounded,
      category: categorySystemAdmin,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
    PermissionDefinition(
      title: 'Migrar graduaÃ§Ãµes',
      description: 'Permite executar migraÃ§Ã£o de graduaÃ§Ãµes.',
      key: 'pode_migrar_graduacoes',
      icon: Icons.workspace_premium_rounded,
      category: categorySystemAdmin,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
    PermissionDefinition(
      title: 'Migrar chamadas',
      description: 'Permite executar migraÃ§Ã£o de chamadas e presenÃ§as.',
      key: 'pode_migrar_chamadas',
      icon: Icons.history_edu_rounded,
      category: categorySystemAdmin,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
    PermissionDefinition(
      title: 'Migrar eventos',
      description: 'Permite executar migraÃ§Ã£o de eventos.',
      key: 'pode_migrar_eventos',
      icon: Icons.event_available_rounded,
      category: categorySystemAdmin,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
    PermissionDefinition(
      title: 'Migrar participaÃ§Ãµes',
      description: 'Permite executar migraÃ§Ã£o de participaÃ§Ãµes de eventos.',
      key: 'pode_migrar_participacoes',
      icon: Icons.emoji_events_rounded,
      category: categorySystemAdmin,
      critical: true,
      adminOnlySuggested: true,
      delegable: false,
    ),
  ];

  static List<Map<String, dynamic>> get allAsMaps =>
      all.map((permission) => permission.toMap()).toList(growable: false);
}
